name: test - report-compatibility-result

on:
  pull_request:
    branches:
      - main
    paths:
      - report-compatibility-result/**
      - .github/workflows/test-report-compatibility-result.yml

concurrency:
  group: test-report-compatibility-result-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORDPRESS_CHART_VERSION: 22.2.8
      APP_SLUG: replicated-actions-ci # from the Replicated QA team

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            **/package-lock.json

      - name: build
        run: make package-report-compatibility-result

      - name: pull helm chart
        run: |
          helm pull oci://registry-1.docker.io/bitnamicharts/wordpress --version ${{ env.WORDPRESS_CHART_VERSION }}

      - name: create-release
        id: create-release
        uses: replicatedhq/replicated-actions/create-release@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          app-slug: ${{ env.APP_SLUG }}
          chart: wordpress-${{ env.WORDPRESS_CHART_VERSION }}.tgz

      - name: test report-compatibility-result
        id: report-compatibility-result
        uses: ./report-compatibility-result
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          app-slug: ${{ env.APP_SLUG }}
          release-sequence: ${{ steps.create-release.outputs.release-sequence }}
          kubernetes-distribution: kind
          kubernetes-version: "1.34.0"
          success: true
          notes: "CI test - compatibility verified successfully"

